[fic]
title = "Untitled 2"
co_authors = ["Sub_Rosa"]
file = "untitled.md"
start_note = "Test"
end_note = "Test"
summary = "Presented without summary"

[tags]
rating = "Mature"
warnings = ["Graphic Depictions Of Violence"]
fandoms = ["呪術廻戦 | Jujutsu Kaisen (Manga)"]
categories = ["F/F"]
relationships = ["Fushiguro Megumi/Inumaki Toge"]
characters = ["Itadori Yuji"]
other = ["Trans Character"]

[meta]
format = "Markdown"
language = "English"
total_chapters = 1

[chapters.01]
url = ""
co_authors = []
title = ""

[chapters.02]
url = ""
co_authors = []
title = ""
